#!/usr/bin/python3

import RPi.GPIO as GPIO
import time
import sys

GPIO.setmode(GPIO.BCM)
GPIO.setup(23, GPIO.IN, GPIO.PUD_UP)

while True:
	print(GPIO.input(23), end="")
	sys.stdout.flush()
	time.sleep(.1)
