#!/usr/bin/python3

import RPi.GPIO as GPIO
import time
import sys

GPIO.setmode(GPIO.BCM)
GPIO.cleanup()

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

def main():
	choice = str(input(""))

	if choice == "on":
		try:
			which=input("")
		except ValueError:
			which=str(input(""))

		if which != "all":
			pin = int(which)
			gpio = list()
			gpio.append(pin)
			GPIO.setup(gpio, GPIO.OUT)
			GPIO.output(gpio, 1)
		elif which == "all":
			gpios = [23, 17, 18]
			for i in gpios:
				i = int(i)
				GPIO.setup(i, GPIO.OUT)
				GPIO.output(i, 1)

	if choice == "off":
		try:
			which=input("")
			print(which)
		except ValueError:
			which=str(input(""))
			print(which)

		if which != "all":
			pin = int(which)
			gpio = list()
			gpio.append(pin)
			GPIO.setup(gpio, GPIO.OUT)
			GPIO.output(gpio, 0)
		elif which == "all":
			gpios = [23, 17, 18]
			for i in gpios:
				i = int(i)
				GPIO.setup(i, GPIO.OUT)
				GPIO.output(i, 0)

	main()

main()

