#!/usr/bin/python3

import RPi.GPIO as GPIO
import time
import sys

GPIO.setmode(GPIO.BCM)
GPIO.setup(23, GPIO.OUT)

GPIO.output(23, 0)

while True:
    time.sleep(1)
    GPIO.output(23, 1)
    time.sleep(1)
    GPIO.output(23, 0)

